worker_processes auto;

events {
    worker_connections 8192;
}

http {
    upstream orderservice_pool {
        least_conn;
        keepalive 200;
        server orderservice1:8080;
        server orderservice2:8080;
        server orderservice3:8080;
        server orderservice4:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass         http://orderservice_pool;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_read_timeout 30s;
            proxy_send_timeout 30s;
        }
    }
}
